### ISSUE TITLE
功能建议：能否增加显示玩家皮肤和披风

### ISSUE THREAD

**Issue by A1Panda** [Aliorpse/personal_html_templates#1]
希望能通过ID获取披风和皮肤#mcinfo

**Comment by Aliorpse** [comment]
您在哪里提issue呢

**Comment by Aliorpse** [comment]
> 希望能通过ID获取披风和皮肤#mcinfo

是要获取披风和皮肤源文件链接吗

**Comment by A1Panda** [comment]
是想要增加披风的显示

**Comment by Aliorpse** [comment]
我使用的接口中并没有找到相应的选项，你或许可以把43行的API这里bust改成full可以在背后看到披风，不过不明显
```js
            skin = (await (await fetch(`https://visage.surgeplay.com/full/${urlData.id}`,{headers:{'User-Agent': 'YunzaiMCPlayerInfo/1.0'}})).arrayBuffer())
```

**Comment by Aliorpse** [comment]
如果你有相关API可以代替我这个，可以在[这个仓库](https://github.com/Aliorpse/karin-plugins-alijs)下新建issue，或者是我的gitee那个仓库新建issue提出，本issue将关闭
